### ISSUE TITLE
Do not crash when the config file isn't writable

### ISSUE THREAD

**Issue by pacien** [TediCross/TediCross#102]
The application crashes when the configuration file isn't writable.
As we discussed on Telegram, this should only cause a warning instead of making the application exit.

This blocks packaging for NixOS.

```
Mar 21 15:38:05 HYLIA systemd[1]: Started TediCross Telegram-Discord bridge service.
Mar 21 15:38:06 HYLIA tedicross[30598]: fs.js:114
Mar 21 15:38:06 HYLIA tedicross[30598]:     throw err;
Mar 21 15:38:06 HYLIA tedicross[30598]:     ^
Mar 21 15:38:06 HYLIA tedicross[30598]: Error: EROFS: read-only file system, open '/nix/store/8pgamvgwzl7gyk3a9xvghsilw8grb844-tedicross-settings.yaml'
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Object.openSync (fs.js:438:3)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Object.writeFileSync (fs.js:1189:35)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Settings.toFile (/nix/store/8yxdf49fwgggl6m8h3pskfl1hmx6bxvw-node-tedicross-0.8.2/lib/node_modules/tedicross/lib/settings/Settings.js:78:6)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Object.<anonymous> (/nix/store/8yxdf49fwgggl6m8h3pskfl1hmx6bxvw-node-tedicross-0.8.2/lib/node_modules/tedicross/main.js:60:10)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Module._compile (internal/modules/cjs/loader.js:701:30)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Module.load (internal/modules/cjs/loader.js:600:32)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
Mar 21 15:38:06 HYLIA tedicross[30598]:     at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
Mar 21 15:38:06 HYLIA systemd[1]: tedicross.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by Suppen** [comment]
This has been fixed in version 0.8.3
