### ISSUE TITLE
Duplicated mapping key

### ISSUE THREAD

**Issue by KilluaFein** [TediCross/TediCross#105]
I have this error when I try to add more bridges: 

```
 npm start

> tedicross@0.8.3 start /home/killua/TediCross
> node main.js


/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: duplicated mapping key at line 26, column -395:
    bridges:
    ^
    at generateError (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at storeMappingPair (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:320:7)
    at readBlockMapping (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:1083:9)
    at composeNode (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:1344:12)
    at readDocument (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:1504:3)
    at loadDocuments (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:1560:5)
    at load (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:1581:19)
    at Object.safeLoad (/home/killua/TediCross/node_modules/js-yaml/lib/js-yaml/loader.js:1603:10)
    at Object.<anonymous> (/home/killua/TediCross/main.js:56:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tedicross@0.8.3 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tedicross@0.8.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

What am I missing? The settings.yaml is correctly formatted.

**Comment by trgwii** [comment]
Can you post your settings.yaml? Please censor out the tokens and secrets first.

**Comment by KilluaFein** [comment]
Well, my bad. I duplicated the keyword "bridges" by accident.
