### ISSUE TITLE
Docker container fails to start

### ISSUE THREAD

**Issue by rbuzzell** [TediCross/TediCross#111]
Using the official docker container I am greeted with the following stack trace.
Is there something I'm missing?

```
> node main.js
fs.js:114
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/opt/TediCross/settings.yaml'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/opt/TediCross/main.js:56:43)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tedicross@0.8.8 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tedicross@0.8.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-24T01_08_03_743Z-debug.log
```

**Comment by rbuzzell** [comment]
I am starting it with the following command modified from the original

Mine
```
docker run \
  -d \
  --restart always \
  --name squawk \
  -v /var/dockerData/tedicross/:/opt/TediCross/data \
  -e TELEGRAM_BOT_TOKEN="TOKEN" \
  -e DISCORD_BOT_TOKEN="TOKEN" \
  tedicross/tedicross
```
Original
```
docker run \
  -v /path/to/data/:/opt/TediCross/data \
  -e TELEGRAM_BOT_TOKEN="Your Telegram token" \
  -e DISCORD_BOT_TOKEN="Your Discord token" \
  tedicross/tedicross
```

**Comment by Suppen** [comment]
Is this still an issue in v0.9.0?

**Comment by rbuzzell** [comment]
I'm running my fork at the moment, give me a few days and I'll swap back to the main project's container.

**Comment by Suppen** [comment]
Closing due to lack of feedback

**Comment by DailytheNoob** [comment]
I have this same issue too, here's my `docker-compose.yml` because that is an infinitely better way to do it:
```
version: '3.3'
services:
    tedicross:
        container_name: Tel-Dis_mirror
        volumes:
            - './data:/data'
        image: tedicross/tedicross
        restart: unless-stopped
```

**Comment by thunderysteak** [comment]
This issue still occurs with the latest docker image
Creating a blank `latestDiscordMessageIds.json` in the data docker volume fixes it and makes it start

**Comment by Treawlony** [comment]
I got the same issue, created an empty json looks like makes it work, however I see this error in logs:

`
Could not read or parse the file /opt/TediCross/data/latestDiscordMessageIds.json: SyntaxError: Unexpected end of JSON input | stdout`

**Comment by SerpentDrago** [comment]
I can confirm running docker on Unraid , got this error , then i created a blank file called latestDiscordMessageIds.json / gave it global read write permissions . and got the bot working . (i'm not concerned about security )
