### ISSUE TITLE
TypeError: Cannot read property 'roles' of undefined since update to 0.9.9

### ISSUE THREAD

**Issue by tux93** [TediCross/TediCross#124]
```
node:1013) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'roles' of undefined
    at handleEntities (/home/ircclient/TediCross/src/telegram2discord/handleEntities.js:69:61)
    at ctx.tediCross.prepared.R.map.bridge (/home/ircclient/TediCross/src/telegram2discord/middlewares.js:589:17)
    at _map (/home/ircclient/TediCross/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/home/ircclient/TediCross/node_modules/ramda/src/map.js:64:14)
    at /home/ircclient/TediCross/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at /home/ircclient/TediCross/node_modules/ramda/src/internal/_curry2.js:22:18
    at f1 (/home/ircclient/TediCross/node_modules/ramda/src/internal/_curry1.js:18:17)
    at addPreparedObj (/home/ircclient/TediCross/src/telegram2discord/middlewares.js:599:3)
    at execute (/home/ircclient/TediCross/node_modules/telegraf/composer.js:352:13)
    at Promise.resolve.handler (/home/ircclient/TediCross/node_modules/telegraf/composer.js:352:49)
(node:1013) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1013) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Since there are no timestamps in the console log I can't tell if there was a specific message type being sent / dropped at the time

**Comment by Suppen** [comment]
Apparently the `serverId` setting I removed in 0.9.9 did more than I thought. It has been fixed in v0.9.10
