### ISSUE TITLE
Telegraf unexpected token

### ISSUE THREAD

**Issue by DailytheNoob** [TediCross/TediCross#125]
Here's the error message:

```
> tedicross@0.9.10 start /home/david/telegram-discord-mirror
> node main.js

/home/david/telegram-discord-mirror/node_modules/telegraf/telegraf.js:27
      ...DEFAULT_OPTIONS,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/david/telegram-discord-mirror/main.js:22:18)

npm ERR! Linux 3.10.0-1062.4.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tedicross@0.9.10 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tedicross@0.9.10 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tedicross package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tedicross
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tedicross
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/david/telegram-discord-mirror/npm-debug.log
```
Here is `npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tedicross@0.9.10~prestart: tedicross@0.9.10
6 silly lifecycle tedicross@0.9.10~prestart: no script for prestart, continuing
7 info lifecycle tedicross@0.9.10~start: tedicross@0.9.10
8 verbose lifecycle tedicross@0.9.10~start: unsafe-perm in lifecycle true
9 verbose lifecycle tedicross@0.9.10~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/david/telegram-discord-mirror/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/david/.local/bin:/home/david/bin
10 verbose lifecycle tedicross@0.9.10~start: CWD: /home/david/telegram-discord-mirror
11 silly lifecycle tedicross@0.9.10~start: Args: [ '-c', 'node main.js' ]
12 silly lifecycle tedicross@0.9.10~start: Returned: code: 1  signal: null
13 info lifecycle tedicross@0.9.10~start: Failed to exec start script
14 verbose stack Error: tedicross@0.9.10 start: `node main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid tedicross@0.9.10
16 verbose cwd /home/david/telegram-discord-mirror
17 error Linux 3.10.0-1062.4.3.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.17.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error tedicross@0.9.10 start: `node main.js`
22 error Exit status 1
23 error Failed at the tedicross@0.9.10 start script 'node main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the tedicross package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs tedicross
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls tedicross
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
node is `v6.17.1`
npm  is `v3.10.10`

I followed the guide for installing this, not sure what went wrong this time, cause I've had it running in the past...

**Comment by Suppen** [comment]
Nodejs 6 is not supported. Please upgrade to at least 8, preferably 12
