### ISSUE TITLE
supports only two chats at a time

### ISSUE THREAD

**Issue by MothGirlMusic** [TediCross/TediCross#126]
hey, i love this bot and its great. but i have a whole network of chats i need to connect to this bot to share discord and telegram chats... and while two chats work perfectly, adding a third gets weird. the bot misses messages and stuff with the third channel [first two are fine].. adding a fourth just kinda makes the fourth just simply not work... so i have to make a bunch of bot instances to cover all chat cases. i wish i only needed one. this is really acting strange and i dont know why.

what should i do to fix it? is it a bug you can fix?

**Comment by MothGirlMusic** [comment]
reading the FAQ, it says its limited by your hardware the number of chats... just before someone answers with that, i have a bunch of instances of tedicross all running on the same machine with all the channels i need to cover running all at once and its doing just fine. so its definately not that. not sure why i can't have them all in one. this is strange.

**Comment by trgwii** [comment]
Any errors in the log?

**Comment by MothGirlMusic** [comment]
Not that I can see, no. 

———
73, KC1KSG

**Comment by Suppen** [comment]
So you have multiple instances of TediCross, each doing one bridge, but you want only one instance with many bridges, is that correct?

What hardware (or specs in case of VM) is this running on? Are the chats very busy?

**Comment by MothGirlMusic** [comment]
i have 3 instances of tedicross using 2 bridges each.. on the same machine no vm just an i7 with 32gb ram running ubuntu server. there's a website but nothing that'd take up that much ram or processor... and i'd like to have all 6 on one instance. but for some reason only the first two work... in any given order. that's why i had to split them up in the first place. i've had them running for over a year now but we're kinda like "cleaning up" now and moving everything over to docker and i'd love to just run one instance of the bot with all the chats working in its own docker. [i love docker] but yeah.. the chats themselves aren't all that crazy. 100-200 people... dead at times... just a few chats for their respective game servers we have on different machines. the discord itself only has around 750 people in it. so very much not super crazy.

i don't know what else i can do besides offer you a copy of my config with all the details bleeped out. [the bots work perfect in their own tedicross instances. so i know the tokens and all that are 100% correct and in order.] but i don't know how helpful that would be.

this is just a super super strange issue. i've never heard of anyone else having it and you know, i'm not blaming the developer or anything. tbh its probably my wonky environment. we're re formatting the entire server to put all our services back on as kind of a yearly "clean up" to make sure we don't have any lose ends not backed up or weird "clever code" running on the systems which would make future deployments ..... that much difficult. its just a small thing but would love for tedi to only take up one container rather than 3... just for the sake of cleanliness and ease of backing up and all that.

and while i'll keep poking at it later tonight, i'd like you to know that i have scoured the web for other bots like this but i want you to know that tedicross is the best. other bots do it on the side but tedicross does one thing and does it really really well. even if i can't solve the issue, we'll continue using the bot.

cheers.

**Comment by Suppen** [comment]
Mighty strange. An i7 (regardless of generation) with 32 GB RAM should be able to handle thousands of bridges. I have one instance with five bridges, and no issues. I have been running a test instance with no issues on a Raspberry Pi Zero, which is basically a potato.

Could you post the versions you are running of nodejs and TediCross? You find the node version with the command `node -v`, and the TediCross version in `package.json`

**Comment by MothGirlMusic** [comment]
node version 10.17.0

TediCross version 0.8.7

**Comment by MothGirlMusic** [comment]
testing the docker image...not sure what this means but i keep getting it even in the older version:

```
(node:16) UnhandledPromiseRejectionWarning: FetchError: request to https://api.telegram.org/botXXXXXXXXXX:XXXXXXXXXXXXXXXXXX/getMe failed, reason: getaddrinfo EAI_AGAIN api.telegram.org api.telegram.org:443

    at ClientRequest.<anonymous> (/opt/TediCross/node_modules/node-fetch/lib/index.js:1455:11)

    at ClientRequest.emit (events.js:189:13)

    at TLSSocket.socketErrorListener (_http_client.js:392:9)

    at TLSSocket.emit (events.js:189:13)

    at emitErrorNT (internal/streams/destroy.js:82:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)

    at process._tickCallback (internal/process/next_tick.js:63:19)

(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MothGirlMusic** [comment]
all i did was copy settings into the attached /opt/TediCross/data volume as it said, and made it writeable and all that. but idk what this error means.

**Comment by Suppen** [comment]
TediCross 0.8.7 was released back in april. The newest version is 0.9.10. Could you try to upgrade?

The error you get means the bot can't contact Telegram's servers for some reason.

**Comment by MothGirlMusic** [comment]
i'll see if i can get the docker to work. maybe the bot api updated and i need to get a new key or make a new bot with bot father? so i'll do that and let you know. i can only assume the docker is the latest version of both node and tedicross.. and its the easiest thing ever to set up and test. just have to figure out why it won't connect. i've seen the error before but i guess it fixed itself so didn't have a reason to look into it.

**Comment by MothGirlMusic** [comment]
i'm not sure what to do about the error. it seems discord starts up first and authorization goes just fine. outputs what i expect it to. then tries discord and instantly crashes. it has internet... i made a new bot just for it with a new token, so it has that to itself just fine. double and triple checked everything is correct.. it just wont work.

**Comment by MothGirlMusic** [comment]
i think it looks like its specifically the SSL/TLS is what it doesn't like. so it is connecting but maybe it doesn't like the SSL cert its getting for some reason its untrusted? i think thats something you'd have to fix in the code tbh. not something i'm doing wrong. as far as i know.

**Comment by MothGirlMusic** [comment]
showing discord working and telegram not
```
         'GET /api/v7/gateway HTTP/1.1\r\nHost: discordapp.com\r\nAuthorization: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\nUser-Agent: DiscordBot (https://github.com/discordjs/discord.js, 11.5.1) Node.js/v10.15.3\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\n\r\n',

        _pendingEncoding: 'latin1',

        server: undefined,

        _server: null,

        ssl: null,

        _requestCert: true,

        _rejectUnauthorized: true,

        parser: null,

        _httpMessage: [Circular],

        [Symbol(res)]: [TLSWrap],

        [Symbol(asyncId)]: 7,

        [Symbol(lastWriteQueueSize)]: 0,

        [Symbol(timeout)]: null,

        [Symbol(kBytesRead)]: 0,

        [Symbol(kBytesWritten)]: 0,

        [Symbol(connect-options)]: [Object] },

     _header:

      'GET /api/v7/gateway HTTP/1.1\r\nHost: discordapp.com\r\nAuthorization: XXXXXXXXXXXXXXXXXX.XXXXXXX\r\nUser-Agent: DiscordBot (https://github.com/discordjs/discord.js, 11.5.1) Node.js/v10.15.3\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\n\r\n',

     _onPendingData: [Function: noopPendingOutput],

     agent:

      Agent {

        _events: [Object],

        _eventsCount: 1,

        _maxListeners: undefined,

        defaultPort: 443,

        protocol: 'https:',

        options: [Object],

        requests: {},

        sockets: [Object],

        freeSockets: {},

        keepAliveMsecs: 1000,

        keepAlive: true,

        maxSockets: Infinity,

        maxFreeSockets: 256,

        maxCachedSessions: 100,

        _sessionCache: [Object] },

     socketPath: undefined,

     timeout: undefined,

     method: 'GET',

     path: '/api/v7/gateway',

     _ended: false,

     res: null,

     aborted: undefined,

     timeoutCb: null,

     upgradeOrConnect: false,

     parser: null,

     maxHeadersCount: null,

     [Symbol(isCorked)]: false,

     [Symbol(outHeadersKey)]:

      [Object: null prototype] {

        host: [Array],

        authorization: [Array],

        'user-agent': [Array],

        'accept-encoding': [Array] } } }

(node:16) UnhandledPromiseRejectionWarning: FetchError: request to https://api.telegram.org/botXXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXX/getMe failed, reason: getaddrinfo EAI_AGAIN api.telegram.org api.telegram.org:443

    at ClientRequest.<anonymous> (/opt/TediCross/node_modules/node-fetch/lib/index.js:1455:11)

    at ClientRequest.emit (events.js:189:13)

    at TLSSocket.socketErrorListener (_http_client.js:392:9)

    at TLSSocket.emit (events.js:189:13)

    at emitErrorNT (internal/streams/destroy.js:82:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)

    at process._tickCallback (internal/process/next_tick.js:63:19)

(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MothGirlMusic** [comment]
i think it just wants like a try/catch inserted into the code.

**Comment by MothGirlMusic** [comment]
also as a follow up completely installing it on some random mac with node and npm.. it still only runs the first two....

**Comment by Suppen** [comment]
The error code is `EAI_AGAIN`, which means the DNS  lookup times out. The bot cannot figure out which IP the domain `api.telegram.org` has. A try/catch will not help. You cannot call someone if you don't know their number.

I fired up the docker image on my own server, and it worked as expected. There must be something wrong with your container's network settings.

Could you try firing up a TediCross container with the following command?
```
docker run --rm -it --entrypoint /usr/local/bin/node tedicross/tedicross:latest
```
then enter the following JS code, which will send an HTTPS request to `api.telegram.org`:
```
https.get("https://api.telegram.org", res => {res.on("error", err => console.error(err)); res.on("data", chunk => console.log(chunk.toString("utf-8"))) });
```

If it works, you should see something like
```
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>
```
Otherwise you will see some kind of error.

**Comment by MothGirlMusic** [comment]
Error:
```
> https.get("https://api.telegram.org", res => {res.on("error", err => console.error(err)); res.on("data", chunk => console.log(chunk.toString("utf-8"))) });
ClientRequest {
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] },
  _events:
   [Object: null prototype] {
     response: { [Function: bound onceWrapper] listener: [Function] },
     socket:
      { [Function: bound onceWrapper] listener: [Function: onSocket] } },
  _eventsCount: 2,
  _maxListeners: undefined,
  output:
   [ 'GET / HTTP/1.1\r\nHost: api.telegram.org\r\nConnection: close\r\n\r\n' ],
  outputEncodings: [ 'latin1' ],
  outputCallbacks: [ [Function: bound onFinish] ],
  outputSize: 61,
  writable: true,
  _last: true,
  chunkedEncoding: false,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: false,
  sendDate: false,
  _removedConnection: false,
  _removedContLen: false,
  _removedTE: false,
  _contentLength: 0,
  _hasBody: true,
  _trailer: '',
  finished: true,
  _headerSent: true,
  socket: null,
  connection: null,
  _header:
   'GET / HTTP/1.1\r\nHost: api.telegram.org\r\nConnection: close\r\n\r\n',
  _onPendingData: [Function: noopPendingOutput],
  agent:
   Agent {
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        members: [] },
     _events: [Object: null prototype] { free: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     defaultPort: 443,
     protocol: 'https:',
     options: { path: null },
     requests: {},
     sockets: { 'api.telegram.org:443::::::::::::::::': [Array] },
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: false,
     maxSockets: Infinity,
     maxFreeSockets: 256,
     maxCachedSessions: 100,
     _sessionCache: { map: {}, list: [] } },
  socketPath: undefined,
  timeout: undefined,
  method: 'GET',
  path: '/',
  _ended: false,
  res: null,
  aborted: undefined,
  timeoutCb: null,
  upgradeOrConnect: false,
  parser: null,
  maxHeadersCount: null,
  [Symbol(isCorked)]: false,
  [Symbol(outHeadersKey)]:
   [Object: null prototype] { host: [ 'Host', 'api.telegram.org' ] } }
> { Error: getaddrinfo EAI_AGAIN api.telegram.org api.telegram.org:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.telegram.org',
  host: 'api.telegram.org',
  port: 443,
  domainEmitter:
   ClientRequest {
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        members: [] },
     _events: [Object: null prototype] { response: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: false,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        alpnProtocol: null,
        authorized: false,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: 'api.telegram.org',
        _readableState: [ReadableState],
        readable: false,
        domain: [Domain],
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData:
         'GET / HTTP/1.1\r\nHost: api.telegram.org\r\nConnection: close\r\n\r\n',
        _pendingEncoding: 'latin1',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: [HTTPParser],
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 184,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: false,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        alpnProtocol: null,
        authorized: false,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: 'api.telegram.org',
        _readableState: [ReadableState],
        readable: false,
        domain: [Domain],
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData:
         'GET / HTTP/1.1\r\nHost: api.telegram.org\r\nConnection: close\r\n\r\n',
        _pendingEncoding: 'latin1',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: [HTTPParser],
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 184,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET / HTTP/1.1\r\nHost: api.telegram.org\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        domain: [Domain],
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/',
     _ended: false,
     res: null,
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser:
      HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': null,
        domain: [Domain],
        _headers: [],
        _url: '',
        socket: [TLSSocket],
        incoming: null,
        outgoing: [Circular],
        maxHeaderPairs: 2000,
        _consumed: false,
        onIncoming: [Function: parserOnIncomingClient],
        [Symbol(isReused)]: false },
     maxHeadersCount: null,
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]: [Object: null prototype] { host: [Array] } },
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] },
  domainThrown: false }
```

**Comment by trgwii** [comment]
There's actually no error in the above post, that's just the HTTP request object

**Comment by Suppen** [comment]
There is an error there: `{ Error: getaddrinfo EAI_AGAIN api.telegram.org api.telegram.org:443 ...`. Again, the DNS lookup fails for some reason

**Comment by MothGirlMusic** [comment]
it does not seem to fail for discord which is strange…

**Comment by Suppen** [comment]
You don't happen to be hosting this in Russia?

**Comment by MothGirlMusic** [comment]
it seems to work only when i create a new bot... but stops working when i reboot or restart the container... and then i need to make a new bot every time i restart.

and no, i'm hosting in USA

**Comment by resynth1943** [comment]
Just hopping in here. @MothGirlMusic which DNS server are you using?

**Comment by MothGirlMusic** [comment]
1.1.1.1 and 1.0.0.1

**Comment by resynth1943** [comment]
Hey dudes, I'm getting this too. For example, Telegram A → Telegram B isn't a thing, when both Telegram groups are listed in the configuration file. The current solution I can see is hosting TediCross alongside Matterbridge, linking the two Telegram channels. Other than this, I could perform some runtime hacks but that's honestly going to be a pain; especially when I don't have *any* knowledge of how the codebase functions. This is gonna be interesting to say the least...
