### ISSUE TITLE
D->T User mentions are not sent as plaintext

### ISSUE THREAD

**Issue by Gimrigz** [TediCross/TediCross#136]
Hey there, I've been having a weird issue recently and I'm not sure if this is something that changed on discord side. Essentially, if trying to relay a Discord message that contains a mention (@bob), on telegram side it will appear as @!12314515 which I suspect is the discord user ID.

It seems like the intend is to send those as plaintext, am I missing something?

Thanks.

**Comment by trgwii** [comment]
We've tested this just now, and we can't seem to make it output an ID like that on the Telegram side, it always outputs the normal username.

Which version of TediCross are you on? You can open package.json and read version in one of the first few lines.

**Comment by Gimrigz** [comment]
Hey! Sorry, I should have given more context.

Previously, I was running on 0.1.0 which I had dockerized myself. Very old version, but it had been working fine for quite a while until it suddenly started outputting these IDs instead of usernames. It changed on its own really, I think about it march/april? Back then, it was using the usermap function which no longer exists. I went ahead and upgraded to the latest version 0.9.11, got rid of my own dockerfile and am using yours, pretty much vanilla.

One thing I've been noticing is the following error message,  repeatedly:

`2020-05-22 04:29:32 [ERR] [First bridge] Could not edit Telegram message: TelegramError: 400: Bad Request: message to edit not found
    at /opt/TediCross/node_modules/telegraf/core/network/client.js:281:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /opt/TediCross/src/discord2telegram/setup.js:277:5 {
  code: 400,
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: message to edit not found'
  },
  description: 'Bad Request: message to edit not found',
  parameters: {},
  on: {
    method: 'editMessageText',
    payload: {
      text: '<b>d-bot</b>\nundefined',
      chat_id: -(REDACTED),
      parse_mode: 'HTML'
    }
  }
}`

I did go back and check the README and adjusted the Telegram bot with botfather to remove privacy mode. That didn't do it.

If you want I can try to run it in debug but otherwise I'm pretty lost. :)

Cheers!

**Comment by Gimrigz** [comment]
I’ve looked into it a bit and I’m not sure the edit messages are related. 

However, all those IDs are @! which apparently indicates a user ID with a nickname attached to it. Seems like those are the unresolved ones.

**Comment by Suppen** [comment]
The edit messages are not related. I don't know why they appear, but they don't seem to do any harm other than spamming the console.

The Telegram bot doesn't need privacy mode off to be able to post to a chat, just to read from it.

I am still unable to replicate this. Is this the case for all users? Or just specific ones?

**Comment by Gimrigz** [comment]
On my server, it is all users. Basically, I use Tedicross with a Discord bot that announces who joins voice channels to relay/notify buddies that gaming is on. In my case, I use Tatsumaki but I replicated it with mee6 as well.

These bots do mentions using the @!1234567 format (so, nicknames) to mention users joining a channel. These are not resolved and relayed as the user id string. You could easily replicate the issue by adding such bot to your server and enabling voice channel notifications for instance.

**Comment by Lulalaby** [comment]
## Automatic issue close

Your issue was automatically closed.
We currently clean-up the issues to keep track of confirmed bugs.
If this bug is still valid, please open a [new issue](https://github.com/TediCross/TediCross/issues/new).

See https://github.com/TediCross/TediCross/issues/256 for more details.
