### ISSUE TITLE
The bot sometimes stops relaying messages from Discord to Telegram

### ISSUE THREAD

**Issue by Chase22** [TediCross/TediCross#15]
I have occasionally the problem that tedi don't sync messages from discord to telegram. 

The problem is easily worked around by restarting tedi on the server.

I got the following error message:

`Error: Connection timed out on method getUpdates`
`Request error: { Error: socket hang up`
`    at createHangUpError (_http_client.js:302:15)`
`    at TLSSocket.socketCloseListener (_http_client.js:334:23)`
`    at emitOne (events.js:101:20)`
`    at TLSSocket.emit (events.js:191:7)`
`    at _handle.close (net.js:509:12)`
`    at TCP.done [as _onclose] (_tls_wrap.js:332:7) code: 'ECONNRESET' }`

**Comment by Suppen** [comment]
I will see what I can do about it in the easter holiday

**Comment by Suppen** [comment]
This particular error is actually the other way. It's from the function which collects messages from Telegram before passing them on to Discord. It automatically retries, so unless you get the error all the time (several times per minute), it's nothing to worry about.

It is true, however, that the Discord side stops relaying messages to Telegram. I will try to get to the bottom of what causes that

**Comment by Suppen** [comment]
TediCross now prints more error messages. Could you please report any errors you find here?

**Comment by Chase22** [comment]
At the last break i had no error messages at all. After restarting i get the message
"Couldn't fetch Telegram messages. Reason: Error: Conflict: terminated by other long poll or webhook"

funnily enough... everything works fine

**Comment by brik** [comment]
Same thing happening here, updated to the latest code, but not getting any error messages when it stops relaying.

**Comment by Suppen** [comment]
@Chase22 That error message means that another bot is using your Telegram bot token. You may have accidently started TediCross twice, or accidently or on purpose tried to use the same token with another bot. If this is not the case, someone else might have aquired your token somehow, in which case you should ask @BotFather for a new one.

You could also try entering https://api.telegram.org/botTOKEN/deleteWebhook (with your actual token substituted for "TOKEN") in your browser.

**Comment by Suppen** [comment]
@Chase22 @brik No error message is also useful information. Probably means the error is in another part of the code than I though. Will look into it

**Comment by Chase22** [comment]
@Suppen the token problem was fixed. apparantly was the bot not stopped correctly. Its now fixed

**Comment by Suppen** [comment]
Is this still happening to people? My instance of the bot has behaved nicely for many weeks now

**Comment by Chase22** [comment]
I just had to restart my instance. It does now run with a rolling log file. So if it crashes again i can provide the error log for it.

**Comment by Suppen** [comment]
Happened to me again... Will add some more debug code when I get home

**Comment by brik** [comment]
Been a long while since it crashed until today: 
Couldn't fetch Telegram messages. Reason: SyntaxError: Unexpected token < in JSON at position 0
Couldn't fetch Telegram messages. Reason: Error: Connection timed out on method getUpdates
Request error: { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketCloseListener (_http_client.js:286:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12) code: 'ECONNRESET' }

**Comment by Chase22** [comment]
Crashed again. I got two different error messages (Sadly without a timestamp)

This one poped up around a thousand times in about a week:
`Couldn't fetch Telegram messages. Reason: SyntaxError: Unexpected token < in JSON at position 0`

the second one came up 10 times in 2 batches (Several messages following each other)
`Request error: { Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:191:7)
    at _handle.close (net.js:509:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7) code: 'ECONNRESET' }`

**Comment by Suppen** [comment]
@Chase22 Those are the wrong way, unfortunately... They are from the Telegram->Discord bridge.

**Comment by Suppen** [comment]
I have now committed a new version which hopefully fixes the issue by upgrading the Discord library I'm using. It is necessary to run `npm install` when you download it, even if you do a git pull.

In case it has not fixed the issue, I have made the logging a bit better. The log messages now include a timestamp and which direction it applies to (Telegram->Discord (D2T) or Discord->Telegram (T2D)). In addition, the bot hopefully sends an error message to the Telegram chat once it detects it cannot relay messages from Discord anymore

I also added a setting: `debug`. If set to `true` (default `false`), the Discord bot will print all its debugging information to the console. It also logs to the terminal if the Discord bot does not have status 'READY'

**Comment by Suppen** [comment]
This has not happened for me since the discord.js update. Has it happened for anyone else?

**Comment by Suppen** [comment]
Closing this due to lack of activity. Assumed to be fixed with the discord.js upgrade

**Comment by Suppen** [comment]
Aaaaand just as I close this issue, I get it again myself....

**Comment by brik** [comment]
I updated my bots to the newest code a couple of days ago, but they still stop relaying after a while. The funny thing is that they all seem to stop at the same time.

**Comment by brik** [comment]
2017-09-14 06:26:24 [ERR]       Couldn't fetch Telegram messages. Reason: SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.res.on.e (/home/kamilla/relay-bot-main/node_modules/teleapiwrapper/lib/bot_api.js:712:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
2017-09-14 06:27:24 [ERR]       Couldn't fetch Telegram messages. Reason: Error: Connection timed out on method getUpdates
    at ClientRequest.req.setTimeout (/home/kamilla/relay-bot-main/node_modules/teleapiwrapper/lib/bot_api.js:695:15)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at TLSSocket.emitTimeout (_http_client.js:630:10)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket.Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:11)
Request error: { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketCloseListener (_http_client.js:286:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:497:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7) code: 'ECONNRESET' }

**Comment by Suppen** [comment]
That's interesting. It probably means the discord servers go down for a moment, or you for some reason can't reach them, and the bot is unable to reconnect. This helps a lot. Thanks!

**Comment by Suppen** [comment]
Based on the error message you posted, which is from the Telegram side, it appears you lost internet connection for a moment. The telegram API is stateless, so it doesn't care and just retries until it works again, but the Discord API doesn't like it

**Comment by molteber** [comment]
`Unexpected token < in JSON at position 0`
Didn't this happen on telegram side when for some reason telegram would give you the data? So instead of json you get a html in return? Should be possible to catch this before the error triggers(?)
@Suppen

**Comment by SkateWarp** [comment]
I just had this problem today. 🙄

**Comment by DragonFlayer** [comment]
I'm actually having the reverse, sometimes messages from telegram to discord stop sending, but from discord to telegram keep happening just fine, after restarting TediCross even if you have "skipOldMessages false" it won't post any of the messages it missed from Telegram

I'm waiting for it to happen again so I can open a ticket for it, seems to be an unhandled exception error from what I last saw  before I restarted, really should have copied it when it happened :C

**Comment by brik** [comment]
It doesn't happen as often anymore, I have to restart it about once a month nowadays. 

This is the last error I got:
2017-12-13 02:44:01 [ERR]       Couldn't fetch Telegram messages. Reason: Error: Connection timed out on method getUpdates
    at ClientRequest.req.setTimeout (/home/kamilla/relay-bot-main/node_modules/teleapiwrapper/lib/bot_api.js:695:15)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at TLSSocket.emitTimeout (_http_client.js:630:10)
    at TLSSocket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket.Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:11)
Request error: { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketCloseListener (_http_client.js:286:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:497:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7) code: 'ECONNRESET' }

**Comment by Suppen** [comment]
It has been a year since this issue was last active, and I haven't heard of it happening since. Closing
