### ISSUE TITLE
Tedicross not splitting TG messages

### ISSUE THREAD

**Issue by xses22** [TediCross/TediCross#179]
Hey I have a little issue. It seems like the bot doesn't split big messages from telegram to discord. It's just ignoring the message sent on tg at all. Is there a setting I missed?

I opened the log file and found an error but not sure if it has something to do with it.

> Feb 25 18:15:53 raspberrypi tedicross[5393]: TypeError: Cannot read property 'text' of undefined
Feb 25 18:15:53 raspberrypi tedicross[5393]:     at handleEntities (/home/pi/TediCross/src/telegram2discord/handleEntities.js:163:36)
Feb 25 18:15:53 raspberrypi tedicross[5393]:     at /home/pi/TediCross/src/telegram2discord/middlewares.js:611:22
Feb 25 18:15:53 raspberrypi tedicross[5393]:     at /home/pi/TediCross/src/telegram2discord/middlewares.js:623:6
Feb 25 18:15:53 raspberrypi tedicross[5393]:     at processTicksAndRejections (node:internal/process/task_queues:94:5)
Feb 25 18:15:53 raspberrypi tedicross[5393]:     at async Promise.all (index 0)
Feb 25 18:15:53 raspberrypi tedicross[5393]:     at async addPreparedObj (/home/pi/TediCross/src/telegram2discord/middlewares.js:520:27)
Feb 25 18:15:53 raspberrypi tedicross[5393]: npm ERR! code 1
Feb 25 18:15:53 raspberrypi tedicross[5393]: npm ERR! path /home/pi/TediCross
Feb 25 18:15:53 raspberrypi tedicross[5393]: npm ERR! command failed
Feb 25 18:15:53 raspberrypi tedicross[5393]: npm ERR! command sh -c node main.js
Feb 25 18:15:53 raspberrypi tedicross[5393]: npm ERR! A complete log of this run can be found in:
Feb 25 18:15:53 raspberrypi tedicross[5393]: npm ERR!     /home/pi/.npm/_logs/2021-02-25T18_15_53_824Z-debug.log

Thanks in advancefor help.

**Comment by trgwii** [comment]
PR's are welcome, it's difficult to correctly split a markdown string, so we haven't attempted it.

**Comment by z8512** [comment]
Just use https://telegra.ph to send long message

**Comment by Lulalaby** [comment]
# Issue Check

- Can this issue be closed
- Does this issue still needs attention

**Comment by Lulalaby** [comment]
## Automatic issue close

Your issue was automatically closed.
We currently clean-up the issues to keep track of confirmed bugs.
If this bug is still valid, please open a [new issue](https://github.com/TediCross/TediCross/issues/new).

See https://github.com/TediCross/TediCross/issues/256 for more details.
