### ISSUE TITLE
TediCross: Telegram interface does not follow when groupchat promoted to supergroup chat

### ISSUE THREAD

**Issue by Magicking** [TediCross/TediCross#183]
# What happened?
A new member got promoted to admin which promoted the current(2 members) group chat to a super(3+ members) group chat.
The service ceased to function.
# What was expected?
The service should have understood the error message saying that the new telegram group chat ID is YYYYYY and update its config regarding the telegram group chat ID ZZZZZZZ and rejoin.

*Note that it was necessary to add the permissions (admin rights) to the bot after he was added the new super group chat
# Circumvention
Kill the service, replace ZZZZZZZ by YYYYYY  in the YAML config file and restart the service.

# Stack trace
```
Attaching to l2p-telegram-bridge_tedi-cross_1
tedi-cross_1  |
tedi-cross_1  | > tedicross@0.10.6 start /opt/TediCross
tedi-cross_1  | > node main.js "-c" "data/settings.yaml"
tedi-cross_1  |
tedi-cross_1  | 2021-04-27 17:32:39 [INFO] Telegram: l2p_bridge_bot (REDACTED)
tedi-cross_1  | 2021-04-27 17:32:40 [INFO] Discord: l2p-bridge (REDACTED)
tedi-cross_1  | (node:16) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message_id' of undefined
tedi-cross_1  |     at addMessageId (/opt/TediCross/src/telegram2discord/middlewares.js:185:50)
tedi-cross_1  |     at execute (/opt/TediCross/node_modules/telegraf/composer.js:370:13)
tedi-cross_1  |     at /opt/TediCross/node_modules/telegraf/composer.js:370:49
tedi-cross_1  |     at execute (/opt/TediCross/node_modules/telegraf/composer.js:370:13)
tedi-cross_1  |     at /opt/TediCross/node_modules/telegraf/composer.js:370:49
tedi-cross_1  |     at addMessageObj (/opt/TediCross/src/telegram2discord/middlewares.js:171:2)
tedi-cross_1  |     at execute (/opt/TediCross/node_modules/telegraf/composer.js:370:13)
tedi-cross_1  |     at /opt/TediCross/node_modules/telegraf/composer.js:370:49
tedi-cross_1  |     at execute (/opt/TediCross/node_modules/telegraf/composer.js:370:13)
tedi-cross_1  |     at /opt/TediCross/node_modules/telegraf/composer.js:370:49
tedi-cross_1  | (Use `node --trace-warnings ...` to show where the warning was created)
tedi-cross_1  | (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
tedi-cross_1  | (node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
tedi-cross_1  | 2021-04-27 17:36:29 [ERR] [l2p-bridge] Telegram did not accept a message: TelegramError: 400: Bad Request: group chat was upgraded to a supergroup chat
tedi-cross_1  |     at /opt/TediCross/node_modules/telegraf/core/network/client.js:281:17
tedi-cross_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
tedi-cross_1  |     at async /opt/TediCross/src/discord2telegram/setup.js:209:25 {
tedi-cross_1  |   code: 400,
tedi-cross_1  |   response: {
tedi-cross_1  |     ok: false,
tedi-cross_1  |     error_code: 400,
tedi-cross_1  |     description: 'Bad Request: group chat was upgraded to a supergroup chat',
tedi-cross_1  |     parameters: { migrate_to_chat_id: YYYYYY}
tedi-cross_1  |   },
tedi-cross_1  |   description: 'Bad Request: group chat was upgraded to a supergroup chat',
tedi-cross_1  |   parameters: { migrate_to_chat_id: YYYYYY},
tedi-cross_1  |   on: {
tedi-cross_1  |     method: 'sendMessage',
tedi-cross_1  |     payload: {
tedi-cross_1  |       chat_id: ZZZZZZZ,
tedi-cross_1  |       text: 'REDACTED',
tedi-cross_1  |       parse_mode: 'HTML'
tedi-cross_1  |     }
tedi-cross_1  |   }
tedi-cross_1  | }
```

**Comment by Lulalaby** [comment]
## Automatic issue close

Your issue was automatically closed.
We currently clean-up the issues to keep track of confirmed bugs.
If this bug is still valid, please open a [new issue](https://github.com/TediCross/TediCross/issues/new).

See https://github.com/TediCross/TediCross/issues/256 for more details.
