### ISSUE TITLE
Bot is Crashing

### ISSUE THREAD

**Issue by itsnotyoutoday** [TediCross/TediCross#194]
The bot seems to be crashing for some reason or another...  any tips?
```

Could not relay a message to Discord on bridge SomeonesDiscord to SomeonesTelegram: Missing Permissions
/home/skee/tedicross/src/telegram2discord/endwares.js:251
                                await dcMessage.edit(messageText, { attachment: prepared.attachment });
                                                ^

TypeError: dcMessage.edit is not a function
    at /home/skee/tedicross/src/telegram2discord/endwares.js:251:21
    at forEach (/home/skee/tedicross/node_modules/ramda/src/forEach.js:53:5)
    at /home/skee/tedicross/node_modules/ramda/src/internal/_checkForMethod.js:25:72
    at /home/skee/tedicross/node_modules/ramda/src/internal/_curry2.js:26:18
    at f1 (/home/skee/tedicross/node_modules/ramda/src/internal/_curry1.js:19:17)
    at edit (/home/skee/tedicross/src/telegram2discord/endwares.js:252:6)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /home/skee/tedicross/src/telegram2discord/endwares.js:269:3
```

**Comment by Suppen** [comment]
The error message says why it crashes: Missing permissions. Make sure the bots have the proper permissions. Sometimes you must set the permissions per channel on Discord

**Comment by itsnotyoutoday** [comment]
Crashed again... no message about permissions this time..

```
/home/skee/tedicross/src/telegram2discord/endwares.js:251
                                await dcMessage.edit(messageText, { attachment: prepared.attachment });
                                                ^

TypeError: dcMessage.edit is not a function
    at /home/skee/tedicross/src/telegram2discord/endwares.js:251:21
    at forEach (/home/skee/tedicross/node_modules/ramda/src/forEach.js:53:5)
    at /home/skee/tedicross/node_modules/ramda/src/internal/_checkForMethod.js:25:72
    at /home/skee/tedicross/node_modules/ramda/src/internal/_curry2.js:26:18
    at f1 (/home/skee/tedicross/node_modules/ramda/src/internal/_curry1.js:19:17)
    at edit (/home/skee/tedicross/src/telegram2discord/endwares.js:252:6)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /home/skee/tedicross/src/telegram2discord/endwares.js:269:3
```

**Comment by LmaoSanchez** [comment]
I am getting the same error as @itsnotyoutoday

**Comment by LmaoSanchez** [comment]
> Crashed again... no message about permissions this time..
> 
> ```
> /home/skee/tedicross/src/telegram2discord/endwares.js:251
>                                 await dcMessage.edit(messageText, { attachment: prepared.attachment });
>                                                 ^
> 
> TypeError: dcMessage.edit is not a function
>     at /home/skee/tedicross/src/telegram2discord/endwares.js:251:21
>     at forEach (/home/skee/tedicross/node_modules/ramda/src/forEach.js:53:5)
>     at /home/skee/tedicross/node_modules/ramda/src/internal/_checkForMethod.js:25:72
>     at /home/skee/tedicross/node_modules/ramda/src/internal/_curry2.js:26:18
>     at f1 (/home/skee/tedicross/node_modules/ramda/src/internal/_curry1.js:19:17)
>     at edit (/home/skee/tedicross/src/telegram2discord/endwares.js:252:6)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
>     at async /home/skee/tedicross/src/telegram2discord/endwares.js:269:3
> ```

(node:17) UnhandledPromiseRejectionWarning: TypeError: dcMessage.edit is not a function
    at /opt/TediCross/src/telegram2discord/endwares.js:251:21
    at forEach (/opt/TediCross/node_modules/ramda/src/forEach.js:53:5)
    at /opt/TediCross/node_modules/ramda/src/internal/_checkForMethod.js:25:72
    at /opt/TediCross/node_modules/ramda/src/internal/_curry2.js:26:18
    at f1 (/opt/TediCross/node_modules/ramda/src/internal/_curry1.js:19:17)
    at edit (/opt/TediCross/src/telegram2discord/endwares.js:252:6)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/TediCross/src/telegram2discord/endwares.js:269:3
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by t0mas5** [comment]
Same problem here, to me it happens where it has to edit a message in the first part of the bridge (for me is telegram) and then the changes shuold be fowarderd to discord but give this error in return.

**Comment by mahdilupo** [comment]
I have some crashing issues too!!

**Comment by gutocarvalho** [comment]
I can confirm that

```
2022-04-08 07:58:55 [LOG] [WS => Shard 0] Heartbeat acknowledged, latency of 149ms.
/Users/gutocarvalho/Documents/storage/projects/bolhatech/bridges/TediCross/dist/telegram2discord/endwares.js:177
                await dcMessage.edit({ content: messageText, attachment: prepared.attachment });
                                ^

TypeError: dcMessage.edit is not a function
    at /Users/gutocarvalho/Documents/storage/projects/bolhatech/bridges/TediCross/dist/telegram2discord/endwares.js:177:33
    at forEach (/Users/gutocarvalho/Documents/storage/projects/bolhatech/bridges/TediCross/node_modules/ramda/src/forEach.js:53:5)
    at /Users/gutocarvalho/Documents/storage/projects/bolhatech/bridges/TediCross/node_modules/ramda/src/internal/_checkForMethod.js:25:72
    at /Users/gutocarvalho/Documents/storage/projects/bolhatech/bridges/TediCross/node_modules/ramda/src/internal/_curry2.js:26:18
    at f1 (/Users/gutocarvalho/Documents/storage/projects/bolhatech/bridges/TediCross/node_modules/ramda/src/internal/_curry1.js:19:17)
    at edit (/Users/gutocarvalho/Documents/storage/projects/bolhatech/bridges/TediCross/dist/telegram2discord/endwares.js:178:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/gutocarvalho/Documents/storage/projects/bolhatech/bridges/TediCross/dist/telegram2discord/endwares.js:192:9

Node.js v17.8.0
```

**Comment by Lulalaby** [comment]
## Automatic issue close

Your issue was automatically closed.
We currently clean-up the issues to keep track of confirmed bugs.
If this bug is still valid, please open a [new issue](https://github.com/TediCross/TediCross/issues/new).

See https://github.com/TediCross/TediCross/issues/256 for more details.
