### ISSUE TITLE
Telegram did not accept a message.

### ISSUE THREAD

**Issue by BanelingRush** [TediCross/TediCross#195]
Keep getting the following error when running from a container.

2021-08-30 16:07:37 [ERR] [First bridge] Telegram did not accept a message: TelegramError: 404: Not Found
    at Telegram.callApi (/opt/TediCross/node_modules/telegraf/lib/core/network/client.js:265:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/TediCross/src/discord2telegram/setup.js:208:25 {
  response: { ok: false, error_code: 404, description: 'Not Found' },
  on: {
    method: 'sendMessage',

/GetInfo doesn't work on on telegram however working fine on discord.

**Comment by BanelingRush** [comment]
Missing telegram token
