### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by crazydave1981** [TediCross/TediCross#216]
Dear team, 

I have done a git pull and a npm install --production.
gave some errors about missing dependencies

root@vmi453468:/home/tedicross-altcoin-cg# sudo npm install --production
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/builders@0.11.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.19.1', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@0.4.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.19.1', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'discord.js@13.6.0',
npm WARN EBADENGINE   required: { node: '>=16.6.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.19.1', npm: '8.5.5' }
npm WARN EBADENGINE }

up to date, audited 184 packages in 16s

found 0 vulnerabilities

/home/tedicross-altcoin-cg/node_modules/discord.js/src/rest/APIRequest.js:34
    agent ??= new https.Agent({ ...this.client.options.http.agent, keepAlive: true });
          ^^^

When running it gives this error. 

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/tedicross-altcoin-cg/node_modules/discord.js/src/rest/RESTManager.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by Suppen** [comment]
The error says what the problem is
```
required: { node: '>=16.0.0', npm: '>=7.0.0' },
current: { node: 'v14.19.1', npm: '8.5.5' }
```
Your nodejs version is old

**Comment by crazydave1981** [comment]
thanks, just updated nodejs and everything is working again. 
Just beeing newbie on linux.
