### ISSUE TITLE
TypeError: dcMessage.edit is not a function

### ISSUE THREAD

**Issue by melwil** [TediCross/TediCross#220]
Got a report from a community I'm running a relay for that this failed. Not sure exactly when it happened or what happened.

The version I'm running is the latest release (v0.11.1)

```
TediCross/dist/telegram2discord/endwares.js:177
                await dcMessage.edit({ content: messageText, attachment: prepared.attachment });
                                ^

TypeError: dcMessage.edit is not a function
    at /home/melwil/git/TediCross/dist/telegram2discord/endwares.js:177:33
    at forEach (/home/melwil/git/TediCross/node_modules/ramda/src/forEach.js:53:5)
    at /home/melwil/git/TediCross/node_modules/ramda/src/internal/_checkForMethod.js:25:72
    at /home/melwil/git/TediCross/node_modules/ramda/src/internal/_curry2.js:26:18
    at f1 (/home/melwil/git/TediCross/node_modules/ramda/src/internal/_curry1.js:19:17)
    at edit (/home/melwil/git/TediCross/dist/telegram2discord/endwares.js:178:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/melwil/git/TediCross/dist/telegram2discord/endwares.js:192:9
```

**Comment by Suppen** [comment]
Known problem. A "fix" is available on branch dcMessage-edit-workaround, and will soon be released as 0.11.2

**Comment by melwil** [comment]
Ah, I see, didn't see anything for it, but if I had searched better I would have found https://github.com/TediCross/TediCross/issues/194

Closing this, then.

**Comment by Lulalaby** [comment]
This should be fixed in the latest version
