### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'message_id')

### ISSUE THREAD

**Issue by zhxq** [TediCross/TediCross#231]
TediCross bot crashes after the following error:

/root/TediCross/dist/telegram2discord/middlewares.js:159
    ctx.tediCross.messageId = ctx.tediCross.message.message_id;
                                                    ^

TypeError: Cannot read properties of undefined (reading 'message_id')
    at addMessageId (/root/TediCross/dist/telegram2discord/middlewares.js:159:53)   
    at execute (/root/TediCross/node_modules/telegraf/lib/composer.js:468:23)
    at /root/TediCross/node_modules/telegraf/lib/composer.js:469:27
    at execute (/root/TediCross/node_modules/telegraf/lib/composer.js:468:23)
    at /root/TediCross/node_modules/telegraf/lib/composer.js:469:27
    at addMessageObj (/root/TediCross/dist/telegram2discord/middlewares.js:148:5)   
    at execute (/root/TediCross/node_modules/telegraf/lib/composer.js:468:23)
    at /root/TediCross/node_modules/telegraf/lib/composer.js:469:27
    at execute (/root/TediCross/node_modules/telegraf/lib/composer.js:468:23)
    at /root/TediCross/node_modules/telegraf/lib/composer.js:469:27

I think better error handling mechanism should be provided (should use a catch exception mechanism and gracefully show the error instead of crashing). I've also seen other properties not found in TediCross, and not all messages on Telegram have the same list of properties, so it may fail when it reads a packet without a given property name.

**Comment by rabfel-hobmet** [comment]
i'm having a similar issue. many crashes and having to ssh in to restart.

**Comment by TarasPriadka** [comment]
Having the same issue, everything crashes randomly. Anyone knows how to fix this?

**Comment by zhxq** [comment]
A workaround - I think TediCross should be able to be added to the system service so that it can restart automatically if it crashes. The good thing is that it doesn't hurt to crash (unlike many other applications) for TediCross as long as it can restart the process.

**Comment by Lulalaby** [comment]
## Automatic issue close

Your issue was automatically closed.
We currently clean-up the issues to keep track of confirmed bugs.
If this bug is still valid, please open a [new issue](https://github.com/TediCross/TediCross/issues/new).

See https://github.com/TediCross/TediCross/issues/256 for more details.
