### ISSUE TITLE
Could not delete Telegram message: TelegramError: 400: Bad Request: xxx not found

### ISSUE THREAD

**Issue by DegenComedian** [TediCross/TediCross#237]
Hi, I am using TediCross `0.11.2` running in Docker `node:16-alpine`

When I delete a message in Telegram it does not get deleted in Discord.
When I delete a message in Discord it works and get successfully deleted in Telegram.

When I try to delete the message `message to delete` in Telegram I get the following log entry

```bash
2022-09-24 14:50:46 [ERR] [degeneric main chat bridge] Could not delete Telegram message: TelegramError: 400: Bad Request: message to delete not found
    at Telegram.callApi (/opt/TediCross/node_modules/telegraf/lib/core/network/client.js:264:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async /opt/TediCross/dist/discord2telegram/setup.js:291:17 {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: message to delete not found'
  },
  on: {
    method: 'deleteMessage',
    payload: { chat_id: -100<SOME CHAT ID I DONT WANT TO REVEAL HERE>, message_id: 101339 }
  }
}
2022-09-24 14:50:46 [WARN] If the previous message was a result of a message being "deleted" on Telegram, you can safely ignore it
```

Thank you for your help
Comedian

**Comment by Lulalaby** [comment]
"##Automatic issue close**

Your issue was automatically closed.
We currently clean-up the issues to keep track of confirmed bugs.
If this bug is still valid, please open a [new issue](https://github.com/TediCross/TediCross/issues/new).

See https://github.com/TediCross/TediCross/issues/256 for more details."
