### ISSUE TITLE
 Cannot find module 'moment'   at  start  script  main.js

### ISSUE THREAD

**Issue by djalmabright** [TediCross/TediCross#63]
node main.js<1s
+ node main.js
module.js:471
    throw err;
    ^
Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/lib/Logger.js:7:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by Suppen** [comment]
Did you do step 4 in the README? Run `npm install` and try again
