### ISSUE TITLE
error startup

### ISSUE THREAD

**Issue by frank1210** [TediCross/TediCross#64]
> tedicross@0.1.0 start /home/bot/TediCross
> node main.js

sh: 1: node: not found

npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! tedicross@0.1.0 start: `node main.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the tedicross@0.1.0 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tedicross package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tedicross
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tedicross
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bot/TediCross/npm-debug.log

i get this after using npm start. Tried #27 by deleting node_modules and issue the install command again but no luck in there

**Comment by Suppen** [comment]
You are using node v4. TediCross requires node 6 (soon 8)

I assume you are using Ubuntu or another Debian flavored Linux distro. This is a common problem with them, as the node version you get by `apt-get install nodejs` is old.

Try the commands `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -` and
`sudo apt-get install -y nodejs`. They should give you node 8

**Comment by frank1210** [comment]
it works!, now when i start i get another error

2018-04-11 08:26:39 [ERR]       Could not authenticate the Discord bot: Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (/home/bot/TediCross/node_modules/discord.js/src/client/ClientManager.js:47:41)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.onClose (/home/bot/TediCross/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:390:10)
    at WebSocket.onClose (/home/bot/TediCross/node_modules/ws/lib/event-target.js:124:16)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at _receiver.cleanup (/home/bot/TediCross/node_modules/ws/lib/websocket.js:220:12)
    at Receiver.cleanup (/home/bot/TediCross/node_modules/ws/lib/receiver.js:535:15)

i double checked the token for the discord bot and they match withone in settings.json

**Comment by Suppen** [comment]
That error does mean the token is wrong. Did a rogue space sneak in? Did you use the Client ID instead of the token?

**Comment by frank1210** [comment]
it was my bad i used app details token isntead of bot token, now its working 100%
