### ISSUE TITLE
about "Could not authenticate the Discord bot"

### ISSUE THREAD

**Issue by yuchanz** [TediCross/TediCross#72]
Hi, I have a question.
On BotFater, I execed the command "/token" ,and select bot name, and got "HTTP API". I inserted TELEGRAM_BOT_TOKEN_HERE here in settings.yaml
Is this wrong?

Executing the command "npm start" will result in the following error:
------------
Clearing old Telegram messages
Using gateway wss://gateway.discord.gg/?v=6&encoding=json
[ws] [connection] Connecting to wss://gateway.discord.gg/?v=6&encoding=json
[ws] [connection] Connected to gateway wss://gateway.discord.gg/?v=6&encoding=json
[ws] [connection] Identifying as a new session
[ws] [connection] Setting a heartbeat interval for 41250ms
[ws] [connection] Server closed the WebSocket connection: 4004
[ws] [connection] Clearing heartbeat interval
[ws] [connection] Tried to identify with an invalid token
[ws] [connection] Clearing heartbeat interval
Could not authenticate the Discord bot: Error: Incorrect login details were provided.
    at WebSocketConnection.client.ws.connection.once.event (/home/botagent/TediCross/node_modules/discord.js/src/client/ClientManager.js:47:41)
    at WebSocketConnection.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at WebSocketConnection.emit (events.js:188:7)
    at WebSocketConnection.onClose (/home/botagent/TediCross/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:390:10)
    at WebSocket.onClose (/home/botagent/TediCross/node_modules/ws/lib/event-target.js:124:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at _receiver.cleanup (/home/botagent/TediCross/node_modules/ws/lib/websocket.js:220:12)
    at Receiver.cleanup (/home/botagent/TediCross/node_modules/ws/lib/receiver.js:535:15)
2018-06-11 16:27:35 [ERR]       Discord status not ready! Status is 'UNKNOWN'
2018-06-11 16:27:35 [INFO]      Telegram: MyBotAgent_bot (619112122)
2018-06-11 16:27:36 [LOG]       Old Telegram messages cleared
2018-06-11 16:27:36 [LOG]       Fetching Telegram updates
2018-06-11 16:27:36 [ERR]       Discord status not ready! Status is 'UNKNOWN'
2018-06-11 16:27:37 [ERR]       Discord status not ready! Status is 'UNKNOWN'

**Comment by molteber** [comment]
Have you added the discord channel id and server id?

**Comment by yuchanz** [comment]
Hi, molteber. I think that I could do it.
Specifically, I did the following things.
1. On Discord, Appearance -> DeveloperMode -> Enabled
2. For server ID, right-click the Server name and Copy ID
3. For channnel ID, right-click the Channel name and Copy ID

**Comment by molteber** [comment]
Ups, i ment; 
Have you added your discord bot credentials too? As described in step 7 here https://github.com/TediCross/TediCross#step-by-step-installation ?

**Comment by yuchanz** [comment]
I was wrong. I succeeded with your advice. I really appreciate it.

**Comment by molteber** [comment]
Np, closing this issue then.
Enjoy TediCross
