### ISSUE TITLE
Error while starting with npm (Windows)

### ISSUE THREAD

**Issue by KittyCatGamers** [TediCross/TediCross#86]
throw generateError(state, message);
  ^
YAMLException: end of the stream or a document separator is expected at line 2, column 3:
      useFirstNameInsteadOfUsername: false
      ^
    at generateError (C:\Users\AwesomeMaster\Pictures\r-u-o-k\shortfilm\Helios\Helios\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (C:\Users\AwesomeMaster\Pictures\r-u-o-k\shortfilm\Helios\Helios\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readDocument (C:\Users\AwesomeMaster\Pictures\r-u-o-k\shortfilm\Helios\Helios\node_modules\js-yaml\lib\js-yaml\loader.js:1512:5)
    at loadDocuments (C:\Users\AwesomeMaster\Pictures\r-u-o-k\shortfilm\Helios\Helios\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at load (C:\Users\AwesomeMaster\Pictures\r-u-o-k\shortfilm\Helios\Helios\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Object.safeLoad (C:\Users\AwesomeMaster\Pictures\r-u-o-k\shortfilm\Helios\Helios\node_modules\js-yaml\lib\js-yaml\loader.js:1591:10)
    at Function.fromFile (C:\Users\AwesomeMaster\Pictures\r-u-o-k\shortfilm\Helios\Helios\lib\settings\Settings.js:257:25)
    at Object.<anonymous> (C:\Users\AwesomeMaster\Pictures\r-u-o-k\shortfilm\Helios\Helios\main.js:34:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tedicross@0.1.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tedicross@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AwesomeMaster\AppData\Roaming\npm-cache\_logs\2018-09-25T06_26_49_716Z-debug.log
[2018-09-25T06_26_49_716Z-debug.log](https://github.com/TediCross/TediCross/files/2414024/2018-09-25T06_26_49_716Z-debug.log)

**Comment by Suppen** [comment]
Looks like your settings file is wrongly formatted. Take a look at `example.settings.yaml` to see how it is supposed to be. The spaces at the beginning of the lines are important. See also https://github.com/TediCross/TediCross#how-do-i-create-more-bridges

**Comment by KittyCatGamers** [comment]
Is there a way i can bridge the bot from telegram without having to type / ?

**Comment by Suppen** [comment]
There are alternative ways of getting the chat ID. The easiest other than using /chatinfo is to extract it from the URL of the group in Telegram's web app.

Any particular reason you can't type /?

**Comment by KittyCatGamers** [comment]
If i was typing a sentence i don't want people to have to include / in it to use the bridge

**Comment by KittyCatGamers** [comment]
Crap i accidentally closed it

**Comment by Suppen** [comment]
So only messages starting with / gets relayed? Sounds like your bot has insufficient permissions. Have you turned off privacy mode on the bot? And made it admin in the group?

A bot with insufficient permissions will relay only messages directed specifically at it. This means commands (messages starting with /), replies to the bot's messages, and messages @mentioning th bot

A bot with correct permissions will relay everything

**Comment by KittyCatGamers** [comment]
I'm very sorry, i will fix that now :D

**Comment by KittyCatGamers** [comment]
Thank you for you're help Suppen :)
