### ISSUE TITLE
discord app won't reply

### ISSUE THREAD

**Issue by cryptoleo79** [TediCross/TediCross#97]
i have tried everything followed everystep correctly and i get this everytime...
I'm stuck, i use a mac by the way

> tedicross@0.1.0 start /Users/criss/Downloads/TediCross-master
> node main.js

2019-01-18 11:35:15 [ERR] Could not authenticate the Discord bot: Error: An invalid token was provided.
    at Promise (/Users/criss/Downloads/TediCross-master/node_modules/discord.js/src/client/rest/RESTMethods.js:34:54)
    at new Promise (<anonymous>)
    at RESTMethods.login (/Users/criss/Downloads/TediCross-master/node_modules/discord.js/src/client/rest/RESTMethods.js:33:12)
    at Client.login (/Users/criss/Downloads/TediCross-master/node_modules/discord.js/src/client/Client.js:279:30)
    at setup (/Users/criss/Downloads/TediCross-master/lib/discord2telegram/setup.js:281:8)
    at Object.<anonymous> (/Users/criss/Downloads/TediCross-master/main.js:58:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
(node:2824) UnhandledPromiseRejectionWarning: Error: Not Found
    at IncomingMessage.res.on (/Users/criss/Downloads/TediCross-master/node_modules/teleapiwrapper/lib/bot_api.js:735:18)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:2824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:2824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-01-18 11:35:16 [ERR] Failed at getting the Telegram bot's me-object: Error: Not Found
    at IncomingMessage.res.on (/Users/criss/Downloads/TediCross-master/node_modules/teleapiwrapper/lib/bot_api.js:735:18)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:2824) UnhandledPromiseRejectionWarning: Error: Not Found
    at IncomingMessage.res.on (/Users/criss/Downloads/TediCross-master/node_modules/teleapiwrapper/lib/bot_api.js:735:18)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:2824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
chiarikurisus-Mac-Pro:TediCross-master criss$

**Comment by Suppen** [comment]
This has been solved in the support group. TediCross did not read the settings file due to it having the wrong name. `settings.yaml.json` or something
